# Generated by Django 4.2 on 2023-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_ans', models.CharField(max_length=100)),
                ('second_ans', models.CharField(max_length=100)),
                ('third_ans', models.CharField(max_length=100)),
                ('fourth_ans', models.CharField(max_length=100)),
                ('fifth_ans', models.CharField(max_length=100)),
                ('sixth_ans', models.CharField(max_length=100)),
            ],
        ),
    ]
