# Generated by Django 4.2.2 on 2023-06-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='eighth_ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='seventh_ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fifth_ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='first_ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fourth_ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='second_ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='sixth_ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='third_ans',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
